# -*- coding: utf-8 -*-
"""Simple Linear Regression Vedu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AWE8rGzryfaQRVX4EiFvs5ixvzf29dC

Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Loading Dataset

"""

dataset=pd.read_csv('Salary_Data.csv')

"""#Splitting the dataset"""

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

"""Now we will spit the dataset into testing and training sets"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

"""#Training the model

"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

"""#Prediction the test set"""

y_pred = regressor.predict(x_test)

"""#Visualizing the training set results"""

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,regressor.predict(x_train),color='blue')
plt.title('Salary vs Experience(Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""#Visualizing the test set reults"""

plt.scatter(x_test,y_test,color='red')
plt.plot(x_train,regressor.predict(x_train),color='blue')
plt.title('Salary vs Experience(Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()